### PR TITLE
added some need property

### PR DESCRIPTION
**Pull request by mmolaei7878**
distanceText,
distanceValue
,durationText,
durationValue,
startAddress,
endAddress

### CODE REVIEW

**Comment by mmolaei7878** [comment]
distanceText,
distanceValue
,durationText,
durationValue,
startAddress,
endAddress

**Comment by YOUDevelop** [comment]
We need this

**Comment by mmolaei7878** [comment]
> We need this

you can use my fork from this repo, i added there these values

**Comment by YOUDevelop** [comment]
> > We need this
> 
> you can use my fork from this repo, i added there these values

Thanks! I will do this.

**Comment by BinniZenobioCordovaLeandro** [comment]
@mmolaei7878 I like your contribution, and I need this feature too, for my project.
In addition:
It's necessary add a 
`decodeEncodedDistance` to return a double value
and
`decodeEncodedDuration` to return a Duration type

**Comment by BinniZenobioCordovaLeandro** [comment]
And it's not necessary 
`distanceText` and `durationText`
because both will be managed in the application using the value double and duration respectively.

**Comment by Dammyololade** [comment]
This has been implemented and will be part of the new release

**Pull request closed without merging**
